version: '3.9'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-proxy
    environment:
      - CF_DNS_API_TOKEN=[DNS_TOKEN]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - [SETUP_PATH]/traefik/config/traefik.yml:/traefik.yml:ro
      - [SETUP_PATH]/traefik/config/acme.json:/acme.json
      - [SETUP_PATH]/traefik/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.[HOST_FQDN]`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=[DASHBOARD_AUTH_HASH]"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.[HOST_FQDN]`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=[HOST_FQDN]"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.[HOST_FQDN]"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - traefik-proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - [SETUP_PATH]/portainer/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.[HOST_FQDN]`)"
      - "traefik.http.routers.[HOSTNAME].entrypoints=http"
      - "traefik.http.routers.[HOSTNAME].rule=Host(`[HOST_FQDN]`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.[HOSTNAME]-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.[HOSTNAME].middlewares=[HOSTNAME]-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.[HOST_FQDN]`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.routers.[HOSTNAME]-secure.entrypoints=https"
      - "traefik.http.routers.[HOSTNAME]-secure.rule=Host(`[HOST_FQDN]`)"
      - "traefik.http.routers.[HOSTNAME]-secure.tls=true"
      - "traefik.http.routers.[HOSTNAME]-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true
