api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml

certificatesResolvers:
  googledomains:
    acme:
      email: [ACME_EMAIL]
      storage: acme.json
      dnsChallenge:
        provider: googledomains
        resolvers:
          - "1.1.4.4:53"
          - "8.8.8.8:53"

tls:
  options:
    default:
      minVersion: VersionTLS12
